version: '3.8'
services:
  app:
      build: .
      depends_on:
          db:
              condition: service_healthy
      environment:
          - DB_HOST=db
          - DB_USER=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB=user-db
          - DB_PORT=3306
          - FLASK_ENV:production
      ports:
          - 5000:5000
      env_file:
          - .env
    
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD-root}
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 2s
      retries: 10
    env_file:
      - .env


volumes:
  mariadb-data:
    driver: local
