version: '3.8'
services:
  app:
      build: .
      stdin_open: true
      tty: true
      depends_on:
          db:
              condition: service_healthy
      environment:
          - DB_HOST=db
          - DB_USER=${DB_USERNAME}
          - DB_PASSWORD=${DB_PASSWORD}
          - DB=user_db
          - DB_PORT=3306
      ports:
          - 5000:5000
    
  db:
    image: mariadb:latest
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      #- mariadb_data:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 2s
      retries: 10


volumes:
  mariadb_data:
    driver: local
