version: '3.8'
services:
  app:
      build: .
      depends_on:
          db:
              condition: service_healthy
      environment:
          - DB_HOST=db
          - DB_USER=root
          - DB_PASSWORD=root
          - DB=user_database
          - DB_PORT=3306
          - SECRET_KEY = {$SECRET_KEY}
      ports:
          - 5000:5000
    
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_database
    ports:
      - "3306:3306"
    volumes:
      #- mariadb_data:/var/lib/mysql
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql
    healthcheck:
      test: "mariadb $$MYSQL_DATABASE -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1;'"
      interval: 2s
      timeout: 2s
      retries: 10


volumes:
  mariadb_data:
    driver: local
